### ISSUE TITLE
compatibility to newer concurrent-ruby version

### ISSUE THREAD

**Issue by mmoll** [Dynflow/dynflow#175]
There's the intention to update concurrent-ruby(-edge) in the FreeBSD ports tree: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204874

Would it be possible to update dynflow to be compatible with 1.0?

**Comment by iNecas** [comment]
dynflow-0.8.9 with updated dependencies has just been pushed to rubygems

**Comment by mmoll** [comment]
ďakujem veľmi pekne!
