### ISSUE TITLE
Compatibility with algebrick 0.7.4

### ISSUE THREAD

**Issue by mmoll** [Dynflow/dynflow#215]
Debian/strech will bring algebrick 0.7.4: https://packages.debian.org/ruby-algebrick

As a consequence (for foreman-proxy plugins, which use the ruby-dynflow package, which in turn uses the gem in that ruby-algebnrick package) either a version of dynflow that's compatible is needed or an updated version of algebrick, which would then need to be placed into Foreman's APT repos.

**Comment by iNecas** [comment]
Thanks for letting me know, I will try to resolve this issue this week.

**Comment by mmoll** [comment]
what's the status here?

**Comment by iNecas** [comment]
It took a while but I've finally found the issue we had with the update of algebrick. This https://github.com/Dynflow/dynflow/pull/231 should resolve thie issue once and for all.

**Comment by adamruzicka** [comment]
Closing this issue since #231 was merged
