### ISSUE TITLE
Equalize #initialize between test and normal world.

### ISSUE THREAD

**Issue by ShimShtein** [Dynflow/dynflow#225]
Right now `Dynflow::World` has a constructor that receives `config` as a parameter, but `Dynflow::Testing::DummyWorld` that is used in tests has a constructor without parameters.

It makes the users write code that is aware to the type of the world.

**Comment by ShimShtein** [comment]
PR submitted: https://github.com/Dynflow/dynflow/pull/226

**Comment by adamruzicka** [comment]
Closing since the PR #226 got merged.
