### ISSUE TITLE
Cannot run dynflowd on Foreman -  warning: conflicting chdir during another chdir block

### ISSUE THREAD

**Issue by rforberger** [Dynflow/dynflow#316]
Hi,

I am trying to run dynflowd in a Foreman docker container in the current working directory /usr/share/foreman according to the systemd unit /lib/system/systemd/dynflowd.service.

My command looks like

```
source /etc/sysconfig/dynflowd
cd /usr/share/foreman && /usr/sbin/dynflowd start &
```

but I get the following error:

```
Dynflow Executor: start in progress
/opt/theforeman/tfm/root/usr/share/gems/gems/daemons-1.2.3/lib/daemons/daemonize.rb:75: warning: conflicting chdir during another chdir block
/opt/theforeman/tfm/root/usr/share/gems/gems/daemons-1.2.3/lib/daemons/daemonize.rb:108: warning: conflicting chdir during another chdir block
dynflow_executor: process with pid 793 started.
```

I am using the ruby from Foreman, version 2.5.3p105.

Dynflowd says it is started, but it exists immediately. 

Any idea why I get this warning and why dynflowd does not keep running?

Thanks in advance.

Best regards,
Ronny

**Comment by s-seitz** [comment]
Any news on this, as we run into the very same problem. Following installed, using foreman-ruby 2.3.1
ii  foreman                            1.20.2-1     amd64        Systems management web interface
ii  foreman-cli                        1.20.2-1     all          metapackage providing hammer CLI for Foreman
ii  foreman-debug                      1.20.2-1     all          provides support utility foreman-debug.
ii  foreman-installer                  1.20.2-1     all          Automated puppet-based installer for The Foreman
ii  foreman-postgresql                 1.20.2-1     all          metapackage providing PostgreSQL dependencies for Foreman
ii  foreman-proxy                      1.20.2-1     all          RESTful proxies for DNS, DHCP, TFTP, and Puppet
ii  foreman-vmware                     1.20.2-1     all          metapackage providing vmware dependencies for Foreman
ii  ruby-dynflow                       1.1.6-1      all          DYNamic workFLOW orchestration engine
ii  ruby-foreman-deface                1.3.2-1      all          Foreman Deface Plugin Dependency
ii  ruby-foreman-hooks                 0.3.14-1     all          Foreman Hooks Plugin
ii  ruby-foreman-remote-execution      1.6.7-1      all          Foreman Remote Execution Plugin
ii  ruby-foreman-remote-execution-core 1.1.3-1      all          Foreman remote execution - core bits
ii  ruby-foreman-setup                 6.0.0-1      all          Foreman Setup Plugin
ii  ruby-foreman-tasks                 0.14.5-1     all          Tasks management engine for Foreman.
ii  ruby-foreman-tasks-core            0.2.5-1      all          Foreman tasks - core bits
ii  ruby-hammer-cli-foreman            0.15.1-1     all          Foreman commands for Hammer
ii  ruby-puppetdb-foreman              5.0.0-1      all          Foreman Puppetdb Plugin
ii  ruby-smart-proxy-dynflow           0.2.1-1      all          Dynflow runtime for Foreman smart proxy
ii  ruby-smart-proxy-dynflow-core      0.2.1-1      all          Dynflow runtime for Foreman smart proxy

**Comment by adamruzicka** [comment]
Dynflowd was replaced with sidekiq based services starting with Foreman 2.0. Current release of Foreman is 2.4, so I would say this is not really relevant anymore. Closing.
